
services:
  todolist:
    image: todolist
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: mysql
    restart: always
    ports:
     - 3307:3306
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=testdb
    volumes:
      - db:/var/lib/mysql

volumes:

  db: